import adminDB from '@/lib/adminDB';
import platformAPI from '@/lib/platformAPI';
import { getSystemPrompt } from '@/utils/systemPrompt';
import { openai } from '@ai-sdk/openai';
import { id, User } from '@instantdb/react-native';
import { generateText } from 'ai';

const DUMMY_INSTANT_APP_ID = '42824120-dd80-4583-a23a-9c62dc936c8e';

export async function POST(req: Request) {
  const { prompt, buildId } = await req.json();

  const token = req.headers.get('RefreshToken');

  if (!token) {
    return Response.json({ message: 'You must be authenticated' }, { status: 400 });
  }
  const user = await adminDB.auth.verifyToken(token);

  if (!user) {
    return Response.json({ message: 'You are not authenticated' }, { status: 401 });
  }
  console.log('User verified');

  try {
    const friendlyTitle = prompt.slice(0, 100);
    const buildId = id();

    console.log('🚀 ~ POST ~ friendlyTitle:', friendlyTitle);
    await createBuild(user, { buildId, friendlyTitle });
    console.log('Build created');

    // Trigger OpenAI to generate the code
    console.log('generateText');

    // THIS ACTUALLY GENERATES THE CODE
    generateText({
      model: openai('gpt-4o'),
      prompt: `${prompt.initialPrompt} When adding the InstandDB connection, use the following Instant App ID: ${DUMMY_INSTANT_APP_ID}`,
      system: getSystemPrompt(),
      onStepFinish: async (step) => {
        console.log('🚀 ~ POST ~ step:', step.text);
        await adminDB
          .asUser({ email: user.email! })
          .transact([adminDB.tx.builds[buildId].update({ code: step.text, isPreviewable: true })]);
      },
    });
    // console.log('after generate text');
    // const text = result.text;
    // console.log('🚀 ~ POST ~ text:', text);

    return Response.json({ buildId });
  } catch (error: any) {
    return Response.json({ success: false, error: 'Internal server error' }, { status: 500 });
  }
}

async function createBuild(
  user: User,
  {
    buildId,
    friendlyTitle,
  }: {
    buildId: string;
    friendlyTitle: string;
  }
) {
  // Create a new Instant App
  const { app: instantApp } = await platformAPI.createApp({
    title: friendlyTitle,
    orgId: process.env.INSTANT_MMA_APPS_ORG_ID!,
  });
  console.log('Create build with Instant App ID: ', instantApp);
  console.log('Build ID: ', buildId);
  console.log('User email: ', user.email);
  console.log('user id: ', user.id);
  // Add the build with the generated Instant App ID and link it to the user
  try {
    const result = await adminDB.asUser({ email: user.email! }).transact([
      adminDB.tx.builds[buildId]
        .create({
          instantAppId: instantApp.id, // instantApp.id,
          code: '', // will be generated by the LLM
          isPreviewable: false,
          title: friendlyTitle,
        })
        .link({ owner: user.id }),
    ]);
    console.log('Build created', result);
  } catch (error: any) {
    console.error('Error creating build', error);
  }
}
