import adminDB from '@/lib/adminDB';
import platformAPI from '@/lib/platformAPI';
import { getSystemPrompt } from '@/utils/systemPrompt';
import { openai } from '@ai-sdk/openai';
import { id, User } from '@instantdb/react-native';
import { convertToModelMessages, streamText, UIMessage } from 'ai';

const DUMMY_INSTANT_APP_ID = '42824120-dd80-4583-a23a-9c62dc936c8e';

export async function POST(req: Request) {
  const token = req.headers.get('refreshtoken');
  if (!token) {
    return Response.json({ message: 'You must be authenticated' }, { status: 400 });
  }
  const user = await adminDB.auth.verifyToken(token);

  if (!user) {
    return Response.json({ message: 'You are not authenticated' }, { status: 401 });
  }

  try {
    const { prompt } = await req.json();
    const buildId = id();

    const friendlyTitle = prompt.initialPrompt.slice(0, 100);
    await createBuild(user, { buildId, friendlyTitle });

    // Trigger OpenAI to generate the code
    const messages: UIMessage[] = [
      {
        role: 'system',
        id: 'system',
        parts: [
          {
            type: 'text',
            text: getSystemPrompt(),
          },
        ],
      },
      {
        role: 'user',
        id: 'user',
        parts: [
          {
            type: 'text',
            text: prompt.initialPrompt,
          },
        ],
      },
      {
        role: 'user',
        id: 'user',
        parts: [
          {
            type: 'text',
            text: `When adding the InstandDB connection, use the following Instant App ID: ${DUMMY_INSTANT_APP_ID}`,
          },
        ],
      },
    ];

    const result = streamText({
      model: openai('gpt-4o'),
      messages: convertToModelMessages(messages),
      onFinish: async ({ text }) => {
        console.log('onFinish');
        await adminDB
          .asUser({ email: user.email! })
          .transact([adminDB.tx.builds[buildId].update({ code: text, isPreviewable: true })]);
      },
    });

    return Response.json({ buildId });
  } catch (error: any) {
    return Response.json({ success: false, error: 'Internal server error' }, { status: 500 });
  }
}

async function createBuild(
  user: User,
  {
    buildId,
    friendlyTitle,
  }: {
    buildId: string;
    friendlyTitle: string;
  }
) {
  // Create a new Instant App
  const { app: instantApp } = await platformAPI.createApp({
    title: friendlyTitle,
    orgId: process.env.INSTANT_MMA_APPS_ORG_ID!,
  });

  // Add the build with the generated Instant App ID and link it to the user
  await adminDB.asUser({ email: user.email! }).transact([
    adminDB.tx.builds[buildId]
      .create({
        instantAppId: DUMMY_INSTANT_APP_ID, // instantApp.id,
        code: '', // will be generated by the LLM
      })
      .link({ owner: user.id }),
  ]);
}
